# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import httpx._exceptions as module_0
import httpx as module_1


def test_case_0():
    var_0 = module_0.request_context()
    assert (
        f"{type(var_0).__module__}.{type(var_0).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_0.gen).__module__}.{type(var_0.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_0.args == ()
    assert var_0.kwds == {}


def test_case_1():
    var_0 = module_0.request_context()
    assert (
        f"{type(var_0).__module__}.{type(var_0).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_0.gen).__module__}.{type(var_0.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_0.args == ()
    assert var_0.kwds == {}
    var_1 = module_0.request_context()
    assert (
        f"{type(var_1).__module__}.{type(var_1).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_1.gen).__module__}.{type(var_1.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_1.args == ()
    assert var_1.kwds == {}
    var_2 = module_0.request_context()
    assert (
        f"{type(var_2).__module__}.{type(var_2).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_2.gen).__module__}.{type(var_2.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_2.args == ()
    assert var_2.kwds == {}
    var_3 = module_0.request_context()
    assert (
        f"{type(var_3).__module__}.{type(var_3).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_3.gen).__module__}.{type(var_3.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_3.args == ()
    assert var_3.kwds == {}
    read_timeout_0 = module_1.ReadTimeout(var_3)
    assert (
        f"{type(read_timeout_0).__module__}.{type(read_timeout_0).__qualname__}"
        == "httpx.ReadTimeout"
    )
    var_4 = module_0.request_context(read_timeout_0)
    assert (
        f"{type(var_4).__module__}.{type(var_4).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_4.gen).__module__}.{type(var_4.gen).__qualname__}"
        == "builtins.generator"
    )
    assert (
        f"{type(var_4.args).__module__}.{type(var_4.args).__qualname__}"
        == "builtins.tuple"
    )
    assert len(var_4.args) == 1
    assert var_4.kwds == {}
    var_5 = module_0.request_context()
    assert (
        f"{type(var_5).__module__}.{type(var_5).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_5.gen).__module__}.{type(var_5.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_5.args == ()
    assert var_5.kwds == {}


def test_case_2():
    none_type_0 = None
    var_0 = module_0.request_context()
    assert (
        f"{type(var_0).__module__}.{type(var_0).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_0.gen).__module__}.{type(var_0.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_0.args == ()
    assert var_0.kwds == {}
    var_1 = module_0.request_context()
    assert (
        f"{type(var_1).__module__}.{type(var_1).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_1.gen).__module__}.{type(var_1.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_1.args == ()
    assert var_1.kwds == {}
    var_2 = module_0.request_context()
    assert (
        f"{type(var_2).__module__}.{type(var_2).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_2.gen).__module__}.{type(var_2.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_2.args == ()
    assert var_2.kwds == {}
    var_3 = module_0.request_context(var_1)
    assert (
        f"{type(var_3).__module__}.{type(var_3).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_3.gen).__module__}.{type(var_3.gen).__qualname__}"
        == "builtins.generator"
    )
    assert (
        f"{type(var_3.args).__module__}.{type(var_3.args).__qualname__}"
        == "builtins.tuple"
    )
    assert len(var_3.args) == 1
    assert var_3.kwds == {}
    var_4 = module_0.request_context(var_1)
    assert (
        f"{type(var_4).__module__}.{type(var_4).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_4.gen).__module__}.{type(var_4.gen).__qualname__}"
        == "builtins.generator"
    )
    assert (
        f"{type(var_4.args).__module__}.{type(var_4.args).__qualname__}"
        == "builtins.tuple"
    )
    assert len(var_4.args) == 1
    assert var_4.kwds == {}
    var_5 = module_0.request_context()
    assert (
        f"{type(var_5).__module__}.{type(var_5).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_5.gen).__module__}.{type(var_5.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_5.args == ()
    assert var_5.kwds == {}
    var_6 = module_0.request_context()
    assert (
        f"{type(var_6).__module__}.{type(var_6).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_6.gen).__module__}.{type(var_6.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_6.args == ()
    assert var_6.kwds == {}
    var_7 = module_0.request_context(var_6)
    assert (
        f"{type(var_7).__module__}.{type(var_7).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_7.gen).__module__}.{type(var_7.gen).__qualname__}"
        == "builtins.generator"
    )
    assert (
        f"{type(var_7.args).__module__}.{type(var_7.args).__qualname__}"
        == "builtins.tuple"
    )
    assert len(var_7.args) == 1
    assert var_7.kwds == {}
    var_8 = module_0.request_context()
    assert (
        f"{type(var_8).__module__}.{type(var_8).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_8.gen).__module__}.{type(var_8.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_8.args == ()
    assert var_8.kwds == {}
    var_9 = module_0.request_context()
    assert (
        f"{type(var_9).__module__}.{type(var_9).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_9.gen).__module__}.{type(var_9.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_9.args == ()
    assert var_9.kwds == {}
    var_10 = module_0.request_context(var_5)
    assert (
        f"{type(var_10).__module__}.{type(var_10).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_10.gen).__module__}.{type(var_10.gen).__qualname__}"
        == "builtins.generator"
    )
    assert (
        f"{type(var_10.args).__module__}.{type(var_10.args).__qualname__}"
        == "builtins.tuple"
    )
    assert len(var_10.args) == 1
    assert var_10.kwds == {}
    var_11 = module_0.request_context()
    assert (
        f"{type(var_11).__module__}.{type(var_11).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_11.gen).__module__}.{type(var_11.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_11.args == ()
    assert var_11.kwds == {}
    var_12 = module_0.request_context()
    assert (
        f"{type(var_12).__module__}.{type(var_12).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_12.gen).__module__}.{type(var_12.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_12.args == ()
    assert var_12.kwds == {}
    var_13 = module_0.request_context(var_3)
    assert (
        f"{type(var_13).__module__}.{type(var_13).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_13.gen).__module__}.{type(var_13.gen).__qualname__}"
        == "builtins.generator"
    )
    assert (
        f"{type(var_13.args).__module__}.{type(var_13.args).__qualname__}"
        == "builtins.tuple"
    )
    assert len(var_13.args) == 1
    assert var_13.kwds == {}
    int_0 = -238
    var_14 = module_0.request_context(int_0)
    assert (
        f"{type(var_14).__module__}.{type(var_14).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_14.gen).__module__}.{type(var_14.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_14.args == (-238,)
    assert var_14.kwds == {}
    var_15 = module_0.request_context()
    assert (
        f"{type(var_15).__module__}.{type(var_15).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_15.gen).__module__}.{type(var_15.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_15.args == ()
    assert var_15.kwds == {}
    h_t_t_p_status_error_0 = module_1.HTTPStatusError(
        none_type_0, request=var_15, response=var_11
    )
    assert (
        f"{type(h_t_t_p_status_error_0).__module__}.{type(h_t_t_p_status_error_0).__qualname__}"
        == "httpx.HTTPStatusError"
    )
    var_16 = module_0.request_context(h_t_t_p_status_error_0)
    assert (
        f"{type(var_16).__module__}.{type(var_16).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_16.gen).__module__}.{type(var_16.gen).__qualname__}"
        == "builtins.generator"
    )
    assert (
        f"{type(var_16.args).__module__}.{type(var_16.args).__qualname__}"
        == "builtins.tuple"
    )
    assert len(var_16.args) == 1
    assert var_16.kwds == {}
    float_0 = 3342.0886
    var_17 = module_0.request_context(var_6)
    assert (
        f"{type(var_17).__module__}.{type(var_17).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_17.gen).__module__}.{type(var_17.gen).__qualname__}"
        == "builtins.generator"
    )
    assert (
        f"{type(var_17.args).__module__}.{type(var_17.args).__qualname__}"
        == "builtins.tuple"
    )
    assert len(var_17.args) == 1
    assert var_17.kwds == {}
    var_18 = module_0.request_context(float_0)
    assert (
        f"{type(var_18).__module__}.{type(var_18).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_18.gen).__module__}.{type(var_18.gen).__qualname__}"
        == "builtins.generator"
    )
    assert (
        f"{type(var_18.args).__module__}.{type(var_18.args).__qualname__}"
        == "builtins.tuple"
    )
    assert len(var_18.args) == 1
    assert var_18.kwds == {}
    var_19 = module_0.request_context(none_type_0)
    assert (
        f"{type(var_19).__module__}.{type(var_19).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_19.gen).__module__}.{type(var_19.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_19.args == (None,)
    assert var_19.kwds == {}
    var_20 = module_0.request_context()
    assert (
        f"{type(var_20).__module__}.{type(var_20).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_20.gen).__module__}.{type(var_20.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_20.args == ()
    assert var_20.kwds == {}
    var_21 = module_0.request_context()
    assert (
        f"{type(var_21).__module__}.{type(var_21).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_21.gen).__module__}.{type(var_21.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_21.args == ()
    assert var_21.kwds == {}
    var_22 = module_0.request_context()
    assert (
        f"{type(var_22).__module__}.{type(var_22).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_22.gen).__module__}.{type(var_22.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_22.args == ()
    assert var_22.kwds == {}
    var_23 = module_0.request_context(var_5)
    assert (
        f"{type(var_23).__module__}.{type(var_23).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_23.gen).__module__}.{type(var_23.gen).__qualname__}"
        == "builtins.generator"
    )
    assert (
        f"{type(var_23.args).__module__}.{type(var_23.args).__qualname__}"
        == "builtins.tuple"
    )
    assert len(var_23.args) == 1
    assert var_23.kwds == {}
    var_24 = module_0.request_context(none_type_0)
    assert (
        f"{type(var_24).__module__}.{type(var_24).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_24.gen).__module__}.{type(var_24.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_24.args == (None,)
    assert var_24.kwds == {}
    var_25 = module_0.request_context()
    assert (
        f"{type(var_25).__module__}.{type(var_25).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_25.gen).__module__}.{type(var_25.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_25.args == ()
    assert var_25.kwds == {}
    var_26 = module_0.request_context()
    assert (
        f"{type(var_26).__module__}.{type(var_26).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_26.gen).__module__}.{type(var_26.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_26.args == ()
    assert var_26.kwds == {}
    var_27 = module_0.request_context()
    assert (
        f"{type(var_27).__module__}.{type(var_27).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_27.gen).__module__}.{type(var_27.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_27.args == ()
    assert var_27.kwds == {}
    var_28 = module_0.request_context()
    assert (
        f"{type(var_28).__module__}.{type(var_28).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_28.gen).__module__}.{type(var_28.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_28.args == ()
    assert var_28.kwds == {}
    var_29 = module_0.request_context()
    assert (
        f"{type(var_29).__module__}.{type(var_29).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_29.gen).__module__}.{type(var_29.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_29.args == ()
    assert var_29.kwds == {}


def test_case_3():
    none_type_0 = None
    protocol_error_0 = module_1.ProtocolError(none_type_0, request=none_type_0)
    assert (
        f"{type(protocol_error_0).__module__}.{type(protocol_error_0).__qualname__}"
        == "httpx.ProtocolError"
    )
    var_0 = module_0.request_context(protocol_error_0)
    assert (
        f"{type(var_0).__module__}.{type(var_0).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_0.gen).__module__}.{type(var_0.gen).__qualname__}"
        == "builtins.generator"
    )
    assert (
        f"{type(var_0.args).__module__}.{type(var_0.args).__qualname__}"
        == "builtins.tuple"
    )
    assert len(var_0.args) == 1
    assert var_0.kwds == {}
    var_1 = module_0.request_context(var_0)
    assert (
        f"{type(var_1).__module__}.{type(var_1).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_1.gen).__module__}.{type(var_1.gen).__qualname__}"
        == "builtins.generator"
    )
    assert (
        f"{type(var_1.args).__module__}.{type(var_1.args).__qualname__}"
        == "builtins.tuple"
    )
    assert len(var_1.args) == 1
    assert var_1.kwds == {}
    var_2 = module_0.request_context()
    assert (
        f"{type(var_2).__module__}.{type(var_2).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_2.gen).__module__}.{type(var_2.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_2.args == ()
    assert var_2.kwds == {}
    var_3 = module_0.request_context(var_2)
    assert (
        f"{type(var_3).__module__}.{type(var_3).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_3.gen).__module__}.{type(var_3.gen).__qualname__}"
        == "builtins.generator"
    )
    assert (
        f"{type(var_3.args).__module__}.{type(var_3.args).__qualname__}"
        == "builtins.tuple"
    )
    assert len(var_3.args) == 1
    assert var_3.kwds == {}
    tuple_0 = (var_2, var_3, var_3, var_2)
    unsupported_protocol_0 = module_1.UnsupportedProtocol(tuple_0)
    var_4 = module_0.request_context()
    assert (
        f"{type(var_4).__module__}.{type(var_4).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_4.gen).__module__}.{type(var_4.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_4.args == ()
    assert var_4.kwds == {}
    tuple_1 = (unsupported_protocol_0,)
    invalid_u_r_l_0 = module_1.InvalidURL(tuple_1)
    var_5 = module_0.request_context(invalid_u_r_l_0)
    assert (
        f"{type(var_5).__module__}.{type(var_5).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_5.gen).__module__}.{type(var_5.gen).__qualname__}"
        == "builtins.generator"
    )
    assert (
        f"{type(var_5.args).__module__}.{type(var_5.args).__qualname__}"
        == "builtins.tuple"
    )
    assert len(var_5.args) == 1
    assert var_5.kwds == {}
    var_6 = module_0.request_context(tuple_0)
    assert (
        f"{type(var_6).__module__}.{type(var_6).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_6.gen).__module__}.{type(var_6.gen).__qualname__}"
        == "builtins.generator"
    )
    assert (
        f"{type(var_6.args).__module__}.{type(var_6.args).__qualname__}"
        == "builtins.tuple"
    )
    assert len(var_6.args) == 1
    assert var_6.kwds == {}
    var_7 = module_0.request_context()
    assert (
        f"{type(var_7).__module__}.{type(var_7).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_7.gen).__module__}.{type(var_7.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_7.args == ()
    assert var_7.kwds == {}


def test_case_4():
    var_0 = module_0.request_context()
    assert (
        f"{type(var_0).__module__}.{type(var_0).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_0.gen).__module__}.{type(var_0.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_0.args == ()
    assert var_0.kwds == {}
    var_1 = module_0.request_context()
    assert (
        f"{type(var_1).__module__}.{type(var_1).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_1.gen).__module__}.{type(var_1.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_1.args == ()
    assert var_1.kwds == {}
    var_2 = module_0.request_context(var_1)
    assert (
        f"{type(var_2).__module__}.{type(var_2).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_2.gen).__module__}.{type(var_2.gen).__qualname__}"
        == "builtins.generator"
    )
    assert (
        f"{type(var_2.args).__module__}.{type(var_2.args).__qualname__}"
        == "builtins.tuple"
    )
    assert len(var_2.args) == 1
    assert var_2.kwds == {}
    var_3 = module_0.request_context()
    assert (
        f"{type(var_3).__module__}.{type(var_3).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_3.gen).__module__}.{type(var_3.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_3.args == ()
    assert var_3.kwds == {}
    var_4 = module_0.request_context()
    assert (
        f"{type(var_4).__module__}.{type(var_4).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_4.gen).__module__}.{type(var_4.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_4.args == ()
    assert var_4.kwds == {}
    var_5 = module_0.request_context(var_1)
    assert (
        f"{type(var_5).__module__}.{type(var_5).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_5.gen).__module__}.{type(var_5.gen).__qualname__}"
        == "builtins.generator"
    )
    assert (
        f"{type(var_5.args).__module__}.{type(var_5.args).__qualname__}"
        == "builtins.tuple"
    )
    assert len(var_5.args) == 1
    assert var_5.kwds == {}
    var_6 = module_0.request_context()
    assert (
        f"{type(var_6).__module__}.{type(var_6).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_6.gen).__module__}.{type(var_6.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_6.args == ()
    assert var_6.kwds == {}
    cookie_conflict_0 = module_1.CookieConflict(var_1)
    assert (
        f"{type(cookie_conflict_0).__module__}.{type(cookie_conflict_0).__qualname__}"
        == "httpx.CookieConflict"
    )
    var_7 = module_0.request_context(var_3)
    assert (
        f"{type(var_7).__module__}.{type(var_7).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_7.gen).__module__}.{type(var_7.gen).__qualname__}"
        == "builtins.generator"
    )
    assert (
        f"{type(var_7.args).__module__}.{type(var_7.args).__qualname__}"
        == "builtins.tuple"
    )
    assert len(var_7.args) == 1
    assert var_7.kwds == {}
    var_8 = module_0.request_context()
    assert (
        f"{type(var_8).__module__}.{type(var_8).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_8.gen).__module__}.{type(var_8.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_8.args == ()
    assert var_8.kwds == {}
    var_9 = module_0.request_context()
    assert (
        f"{type(var_9).__module__}.{type(var_9).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_9.gen).__module__}.{type(var_9.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_9.args == ()
    assert var_9.kwds == {}
    var_10 = module_0.request_context()
    assert (
        f"{type(var_10).__module__}.{type(var_10).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_10.gen).__module__}.{type(var_10.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_10.args == ()
    assert var_10.kwds == {}
    var_11 = module_0.request_context()
    assert (
        f"{type(var_11).__module__}.{type(var_11).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_11.gen).__module__}.{type(var_11.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_11.args == ()
    assert var_11.kwds == {}
    var_12 = module_0.request_context()
    assert (
        f"{type(var_12).__module__}.{type(var_12).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_12.gen).__module__}.{type(var_12.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_12.args == ()
    assert var_12.kwds == {}
    var_13 = module_0.request_context()
    assert (
        f"{type(var_13).__module__}.{type(var_13).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_13.gen).__module__}.{type(var_13.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_13.args == ()
    assert var_13.kwds == {}
    var_14 = module_0.request_context()
    assert (
        f"{type(var_14).__module__}.{type(var_14).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_14.gen).__module__}.{type(var_14.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_14.args == ()
    assert var_14.kwds == {}
    var_15 = module_0.request_context(var_12)
    assert (
        f"{type(var_15).__module__}.{type(var_15).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_15.gen).__module__}.{type(var_15.gen).__qualname__}"
        == "builtins.generator"
    )
    assert (
        f"{type(var_15.args).__module__}.{type(var_15.args).__qualname__}"
        == "builtins.tuple"
    )
    assert len(var_15.args) == 1
    assert var_15.kwds == {}
    var_16 = module_0.request_context()
    assert (
        f"{type(var_16).__module__}.{type(var_16).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_16.gen).__module__}.{type(var_16.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_16.args == ()
    assert var_16.kwds == {}
    var_17 = module_0.request_context()
    assert (
        f"{type(var_17).__module__}.{type(var_17).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_17.gen).__module__}.{type(var_17.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_17.args == ()
    assert var_17.kwds == {}
    var_18 = module_0.request_context()
    assert (
        f"{type(var_18).__module__}.{type(var_18).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_18.gen).__module__}.{type(var_18.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_18.args == ()
    assert var_18.kwds == {}
    var_19 = module_0.request_context()
    assert (
        f"{type(var_19).__module__}.{type(var_19).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_19.gen).__module__}.{type(var_19.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_19.args == ()
    assert var_19.kwds == {}
    var_20 = module_0.request_context()
    assert (
        f"{type(var_20).__module__}.{type(var_20).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_20.gen).__module__}.{type(var_20.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_20.args == ()
    assert var_20.kwds == {}
    var_21 = module_0.request_context()
    assert (
        f"{type(var_21).__module__}.{type(var_21).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_21.gen).__module__}.{type(var_21.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_21.args == ()
    assert var_21.kwds == {}
    var_22 = module_0.request_context(var_3)
    assert (
        f"{type(var_22).__module__}.{type(var_22).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_22.gen).__module__}.{type(var_22.gen).__qualname__}"
        == "builtins.generator"
    )
    assert (
        f"{type(var_22.args).__module__}.{type(var_22.args).__qualname__}"
        == "builtins.tuple"
    )
    assert len(var_22.args) == 1
    assert var_22.kwds == {}
    var_23 = module_0.request_context()
    assert (
        f"{type(var_23).__module__}.{type(var_23).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_23.gen).__module__}.{type(var_23.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_23.args == ()
    assert var_23.kwds == {}
    var_24 = module_0.request_context()
    assert (
        f"{type(var_24).__module__}.{type(var_24).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_24.gen).__module__}.{type(var_24.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_24.args == ()
    assert var_24.kwds == {}
    var_25 = module_0.request_context(cookie_conflict_0)
    assert (
        f"{type(var_25).__module__}.{type(var_25).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_25.gen).__module__}.{type(var_25.gen).__qualname__}"
        == "builtins.generator"
    )
    assert (
        f"{type(var_25.args).__module__}.{type(var_25.args).__qualname__}"
        == "builtins.tuple"
    )
    assert len(var_25.args) == 1
    assert var_25.kwds == {}
    var_26 = module_0.request_context()
    assert (
        f"{type(var_26).__module__}.{type(var_26).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_26.gen).__module__}.{type(var_26.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_26.args == ()
    assert var_26.kwds == {}
    var_27 = module_0.request_context()
    assert (
        f"{type(var_27).__module__}.{type(var_27).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_27.gen).__module__}.{type(var_27.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_27.args == ()
    assert var_27.kwds == {}


def test_case_5():
    stream_consumed_0 = module_1.StreamConsumed()
    assert (
        f"{type(stream_consumed_0).__module__}.{type(stream_consumed_0).__qualname__}"
        == "httpx.StreamConsumed"
    )
    var_0 = module_0.request_context(stream_consumed_0)
    assert (
        f"{type(var_0).__module__}.{type(var_0).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_0.gen).__module__}.{type(var_0.gen).__qualname__}"
        == "builtins.generator"
    )
    assert (
        f"{type(var_0.args).__module__}.{type(var_0.args).__qualname__}"
        == "builtins.tuple"
    )
    assert len(var_0.args) == 1
    assert var_0.kwds == {}
    var_1 = module_0.request_context()
    assert (
        f"{type(var_1).__module__}.{type(var_1).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_1.gen).__module__}.{type(var_1.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_1.args == ()
    assert var_1.kwds == {}
    var_2 = module_0.request_context()
    assert (
        f"{type(var_2).__module__}.{type(var_2).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_2.gen).__module__}.{type(var_2.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_2.args == ()
    assert var_2.kwds == {}
    var_3 = module_0.request_context()
    assert (
        f"{type(var_3).__module__}.{type(var_3).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_3.gen).__module__}.{type(var_3.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_3.args == ()
    assert var_3.kwds == {}
    bool_0 = False
    protocol_error_0 = module_1.ProtocolError(bool_0, request=bool_0)
    var_4 = module_0.request_context()
    assert (
        f"{type(var_4).__module__}.{type(var_4).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_4.gen).__module__}.{type(var_4.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_4.args == ()
    assert var_4.kwds == {}
    var_5 = module_0.request_context()
    assert (
        f"{type(var_5).__module__}.{type(var_5).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_5.gen).__module__}.{type(var_5.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_5.args == ()
    assert var_5.kwds == {}


def test_case_6():
    stream_closed_0 = module_1.StreamClosed()
    assert (
        f"{type(stream_closed_0).__module__}.{type(stream_closed_0).__qualname__}"
        == "httpx.StreamClosed"
    )
    var_0 = module_0.request_context()
    assert (
        f"{type(var_0).__module__}.{type(var_0).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_0.gen).__module__}.{type(var_0.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_0.args == ()
    assert var_0.kwds == {}
    var_1 = module_0.request_context(stream_closed_0)
    assert (
        f"{type(var_1).__module__}.{type(var_1).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_1.gen).__module__}.{type(var_1.gen).__qualname__}"
        == "builtins.generator"
    )
    assert (
        f"{type(var_1.args).__module__}.{type(var_1.args).__qualname__}"
        == "builtins.tuple"
    )
    assert len(var_1.args) == 1
    assert var_1.kwds == {}
    var_2 = module_0.request_context()
    assert (
        f"{type(var_2).__module__}.{type(var_2).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_2.gen).__module__}.{type(var_2.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_2.args == ()
    assert var_2.kwds == {}
    var_3 = module_0.request_context()
    assert (
        f"{type(var_3).__module__}.{type(var_3).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_3.gen).__module__}.{type(var_3.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_3.args == ()
    assert var_3.kwds == {}
    var_4 = module_0.request_context(var_1)
    assert (
        f"{type(var_4).__module__}.{type(var_4).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_4.gen).__module__}.{type(var_4.gen).__qualname__}"
        == "builtins.generator"
    )
    assert (
        f"{type(var_4.args).__module__}.{type(var_4.args).__qualname__}"
        == "builtins.tuple"
    )
    assert len(var_4.args) == 1
    assert var_4.kwds == {}
    var_5 = module_0.request_context()
    assert (
        f"{type(var_5).__module__}.{type(var_5).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_5.gen).__module__}.{type(var_5.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_5.args == ()
    assert var_5.kwds == {}
    remote_protocol_error_0 = module_1.RemoteProtocolError(var_5, request=var_5)
    var_6 = module_0.request_context()
    assert (
        f"{type(var_6).__module__}.{type(var_6).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_6.gen).__module__}.{type(var_6.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_6.args == ()
    assert var_6.kwds == {}
    connect_timeout_0 = module_1.ConnectTimeout(var_5, request=remote_protocol_error_0)
    var_7 = module_0.request_context(connect_timeout_0)
    assert (
        f"{type(var_7).__module__}.{type(var_7).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_7.gen).__module__}.{type(var_7.gen).__qualname__}"
        == "builtins.generator"
    )
    assert (
        f"{type(var_7.args).__module__}.{type(var_7.args).__qualname__}"
        == "builtins.tuple"
    )
    assert len(var_7.args) == 1
    assert var_7.kwds == {}
    var_8 = module_0.request_context()
    assert (
        f"{type(var_8).__module__}.{type(var_8).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_8.gen).__module__}.{type(var_8.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_8.args == ()
    assert var_8.kwds == {}
    var_9 = module_0.request_context()
    assert (
        f"{type(var_9).__module__}.{type(var_9).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_9.gen).__module__}.{type(var_9.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_9.args == ()
    assert var_9.kwds == {}
    var_10 = module_0.request_context()
    assert (
        f"{type(var_10).__module__}.{type(var_10).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_10.gen).__module__}.{type(var_10.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_10.args == ()
    assert var_10.kwds == {}


def test_case_7():
    var_0 = module_0.request_context()
    assert (
        f"{type(var_0).__module__}.{type(var_0).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_0.gen).__module__}.{type(var_0.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_0.args == ()
    assert var_0.kwds == {}
    var_1 = module_0.request_context()
    assert (
        f"{type(var_1).__module__}.{type(var_1).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_1.gen).__module__}.{type(var_1.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_1.args == ()
    assert var_1.kwds == {}
    var_2 = module_0.request_context()
    assert (
        f"{type(var_2).__module__}.{type(var_2).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_2.gen).__module__}.{type(var_2.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_2.args == ()
    assert var_2.kwds == {}
    response_not_read_0 = module_1.ResponseNotRead()
    assert (
        f"{type(response_not_read_0).__module__}.{type(response_not_read_0).__qualname__}"
        == "httpx.ResponseNotRead"
    )
    var_3 = module_0.request_context(response_not_read_0)
    assert (
        f"{type(var_3).__module__}.{type(var_3).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_3.gen).__module__}.{type(var_3.gen).__qualname__}"
        == "builtins.generator"
    )
    assert (
        f"{type(var_3.args).__module__}.{type(var_3.args).__qualname__}"
        == "builtins.tuple"
    )
    assert len(var_3.args) == 1
    assert var_3.kwds == {}
    var_4 = module_0.request_context()
    assert (
        f"{type(var_4).__module__}.{type(var_4).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_4.gen).__module__}.{type(var_4.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_4.args == ()
    assert var_4.kwds == {}
    var_5 = module_0.request_context()
    assert (
        f"{type(var_5).__module__}.{type(var_5).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_5.gen).__module__}.{type(var_5.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_5.args == ()
    assert var_5.kwds == {}
    var_6 = module_0.request_context()
    assert (
        f"{type(var_6).__module__}.{type(var_6).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_6.gen).__module__}.{type(var_6.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_6.args == ()
    assert var_6.kwds == {}
    var_7 = module_0.request_context()
    assert (
        f"{type(var_7).__module__}.{type(var_7).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_7.gen).__module__}.{type(var_7.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_7.args == ()
    assert var_7.kwds == {}
    var_8 = module_0.request_context()
    assert (
        f"{type(var_8).__module__}.{type(var_8).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_8.gen).__module__}.{type(var_8.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_8.args == ()
    assert var_8.kwds == {}
    var_9 = module_0.request_context()
    assert (
        f"{type(var_9).__module__}.{type(var_9).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_9.gen).__module__}.{type(var_9.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_9.args == ()
    assert var_9.kwds == {}
    var_10 = module_0.request_context()
    assert (
        f"{type(var_10).__module__}.{type(var_10).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_10.gen).__module__}.{type(var_10.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_10.args == ()
    assert var_10.kwds == {}
    var_11 = module_0.request_context(var_8)
    assert (
        f"{type(var_11).__module__}.{type(var_11).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_11.gen).__module__}.{type(var_11.gen).__qualname__}"
        == "builtins.generator"
    )
    assert (
        f"{type(var_11.args).__module__}.{type(var_11.args).__qualname__}"
        == "builtins.tuple"
    )
    assert len(var_11.args) == 1
    assert var_11.kwds == {}
    var_12 = module_0.request_context()
    assert (
        f"{type(var_12).__module__}.{type(var_12).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_12.gen).__module__}.{type(var_12.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_12.args == ()
    assert var_12.kwds == {}
    var_13 = module_0.request_context(var_8)
    assert (
        f"{type(var_13).__module__}.{type(var_13).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_13.gen).__module__}.{type(var_13.gen).__qualname__}"
        == "builtins.generator"
    )
    assert (
        f"{type(var_13.args).__module__}.{type(var_13.args).__qualname__}"
        == "builtins.tuple"
    )
    assert len(var_13.args) == 1
    assert var_13.kwds == {}
    var_14 = module_0.request_context()
    assert (
        f"{type(var_14).__module__}.{type(var_14).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_14.gen).__module__}.{type(var_14.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_14.args == ()
    assert var_14.kwds == {}
    var_15 = module_0.request_context()
    assert (
        f"{type(var_15).__module__}.{type(var_15).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_15.gen).__module__}.{type(var_15.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_15.args == ()
    assert var_15.kwds == {}
    var_16 = module_0.request_context()
    assert (
        f"{type(var_16).__module__}.{type(var_16).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_16.gen).__module__}.{type(var_16.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_16.args == ()
    assert var_16.kwds == {}
    var_17 = module_0.request_context(var_7)
    assert (
        f"{type(var_17).__module__}.{type(var_17).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_17.gen).__module__}.{type(var_17.gen).__qualname__}"
        == "builtins.generator"
    )
    assert (
        f"{type(var_17.args).__module__}.{type(var_17.args).__qualname__}"
        == "builtins.tuple"
    )
    assert len(var_17.args) == 1
    assert var_17.kwds == {}
    var_18 = module_0.request_context()
    assert (
        f"{type(var_18).__module__}.{type(var_18).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_18.gen).__module__}.{type(var_18.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_18.args == ()
    assert var_18.kwds == {}
    var_19 = module_0.request_context()
    assert (
        f"{type(var_19).__module__}.{type(var_19).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_19.gen).__module__}.{type(var_19.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_19.args == ()
    assert var_19.kwds == {}


def test_case_8():
    var_0 = module_0.request_context()
    assert (
        f"{type(var_0).__module__}.{type(var_0).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_0.gen).__module__}.{type(var_0.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_0.args == ()
    assert var_0.kwds == {}
    var_1 = module_0.request_context()
    assert (
        f"{type(var_1).__module__}.{type(var_1).__qualname__}"
        == "contextlib._GeneratorContextManager"
    )
    assert (
        f"{type(var_1.gen).__module__}.{type(var_1.gen).__qualname__}"
        == "builtins.generator"
    )
    assert var_1.args == ()
    assert var_1.kwds == {}
    decoding_error_0 = module_1.DecodingError(var_0, request=var_0)
    assert (
        f"{type(decoding_error_0).__module__}.{type(decoding_error_0).__qualname__}"
        == "httpx.DecodingError"
    )
    var_2 = module_0.request_context(decoding_error_0)
    var_3 = module_0.request_context()
    request_not_read_0 = module_1.RequestNotRead()
    var_4 = module_0.request_context(var_3)
    var_5 = module_0.request_context()
    var_6 = module_0.request_context()
    dict_0 = {var_2: var_0, var_0: request_not_read_0}
    var_7 = module_0.request_context()
    var_8 = module_0.request_context()
    var_9 = module_0.request_context()
    var_10 = module_0.request_context()
    var_11 = module_0.request_context(var_4)
    var_12 = module_0.request_context()
    var_13 = module_0.request_context(dict_0)
    none_type_0 = None
    var_14 = module_0.request_context(none_type_0)
